# Generated by Django 3.1.1 on 2021-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('watsapp', models.CharField(blank=True, max_length=255, null=True, verbose_name='watsapp')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='instagram')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='telegram')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
