# Generated by Django 3.1.1 on 2021-04-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='watsapp',
            new_name='whatsapp',
        ),
    ]
