# Generated by Django 3.1.1 on 2021-04-03 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('src', models.ImageField(height_field='height', max_length=255, upload_to='photos', width_field='width')),
                ('is_grid', models.BooleanField(default=False)),
                ('is_main_screen', models.BooleanField(default=False)),
                ('is_about_preview', models.BooleanField(default=False)),
                ('album_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.album')),
                ('album_preview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preview', to='albums.album')),
            ],
        ),
    ]
