# Generated by Django 3.1.1 on 2020-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.IntegerField(),
        ),
    ]
