# Generated by Django 3.1.1 on 2021-03-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='album_id',
        ),
    ]
