# Generated by Django 3.1.1 on 2020-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20201012_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='src',
        ),
        migrations.AddField(
            model_name='photo',
            name='binary',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos/%Y.%m.%d'),
        ),
    ]
