# Generated by Django 3.1.1 on 2020-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201017_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='binary',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos/'),
        ),
    ]
