# Generated by Django 3.1.1 on 2020-10-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20201018_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(height_field='height', max_length=255, upload_to='photos', width_field='width'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
