# Generated by Django 3.1.1 on 2020-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20201024_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_main_screen',
            field=models.BooleanField(default=False),
        ),
    ]
